### ISSUE TITLE
Example of Delegated Inception and Delegated Rotation?

### ISSUE THREAD

**Issue by FrankC01** [WebOfTrust/keriox#5]
Looking at the EventMsgBuilder it is not clear for Dip what the `delegator` field is to be set to?

Is it the IdentifierPrefix for the delegator which previously had been Incepted? In other words, do I take the IdentifierPrefix of the result of inception for the Delegator keys and use at the `delegator` for the keys I'm Dip'ing so to speak?

**Comment by SmithSamuelM** [comment]
Delegation in KERI is cooperative. A delegate inception event is anchored in the Delegator's KEL. The delegator field is a reference to the Delegator so a validator can look up the anchor. When replaying a KEL the the sequence number and SAID of the event in the Delegators KEL is provided as an attachment.

See this code in keripy:
Baser.cloneEvtMsg
```python
...
# add authorizer (delegator/issure) source seal event couple to attachments
        couple = self.getAes(dgkey)
        if couple is not None:
            atc.extend(coring.Counter(code=coring.CtrDex.SealSourceCouples,
                                      count=1).qb64b)
            atc.extend(couple)
```

**Comment by SmithSamuelM** [comment]
In keripy look in src/keri/app.delegating.py to see how a delegate handles associated events from delegator

**Comment by FrankC01** [comment]
So in the context of the EventMsgBuild in Rust library:

1. Inception for Delegator
2. DelegatedInception for the Delegate with providing the Delegator Prefix 

Guess the other question is the Rust KERI (this repo) being maintained?

**Comment by blelump** [comment]
@FrankC01 , yes, it is actively maintained under https://github.com/THCLab/keriox . We've moved the codebase due to license change to a more strict one.

**Comment by FrankC01** [comment]
@blelump Should I put this issue there instead? You're response is about my last question about liveliness of repo, but not confirming my comment about EventMsgBuild usage....

**Comment by FrankC01** [comment]
Moved to https://github.com/THCLab/keriox/issues/20
