### ISSUE TITLE
Proposal to rename master to main. Add dev branch.

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/keriox#6]
- [x] rename master to main in settings
- [ ] create dev branch from main
- [x] update CI settings

**Comment by trentlarson** [comment]
👍 on the rename.

Probably the same on update CI but not sure what it means.

As for a 'dev' branch: I suggest we do not create a long-lived "dev" branch. I know it's part of the popular Git Flow model and I can see the utility for a time when there is a mature workflow with releases that are coordinated and changed across teams; however, it can cause confusion about where features reside, and it adds overhead of a group decision and a manual merge to get that work to the main branch. I would say the cost isn't worth the extra effort at this stage.

I suggest people feature branches for each new set of work, similar to GitHub Flow. After releases, if there are smaller stability changes that diverge from main then the group can create a release branch. The fewer shared branches, the simpler the coordination.

**Comment by m00sey** [comment]
@trentlarson thank you for the follow up. I'll make those changes
